### ISSUE TITLE
Support running network prediction on an OpenGL texture

### ISSUE THREAD

**Issue by bschwind** [alianse777/darknet-rust#15]
Hi, thanks for creating these bindings! I wanted to run a darknet network on an OpenGL texture which I already have in GPU memory, so the round-trip from GPU to CPU and back was a bit heavy for me (as well as the CPU operations to put the image into the right format that darknet expects).

I have a prototype working, but I'm not sure how best to contribute it, and I want to know if it's desired from others or not.

This repo points to a somewhat old version of darknet (`04b0b15`), but I made my modifications based on that commit. If we were to create new bindings, we would either have to point this repo's submodule to a fork which contains the OpenGL code, or merge the OpenGL work upstream and base it on the latest `master` branch. In that case, the bindings here would probably need to be updated and it could potentially be more work than expected.

What would you recommend I do?

After all that, the higher level `darknet` crate would then need to be modified with new functions to support running the network from a texture, but that part is pretty easy.

**Comment by alianse777** [comment]
Closing since it is probably better to ask in main darknet repo.
